name: nn_mal
dependencies:
- python=3.6
- numpy
- pandas
- pip:
  - pybloomfiltermmap
  - sklearn
  - lief
  - scipy
  - https://download.pytorch.org/whl/cu101/torch-1.4.0-cp36-cp36m-linux_x86_64.whl
  - torchvision
